singleuser:
  profileList:
    - display_name: "Basic Data Science Environment"
      description: "Python, R, Julia, Wolfwarm Alpha, MATLAB"
      kubespawner_override:
        image: 
      default: true
    - display_name: "GPGPU Environment - NVIDIA"
      description: "NVIDIA A30 24G or NVIDIA A40 40G <H>"
      kubespawner_override:
        image: 
  defaultUrl: "/lab"


cull:
  enabled: true
  timeout: 60
  every: 60

hub:
  config:
    GenericOAuthenticator:
      client_id: 
      client_secret: 
      oauth_callback_url: 
      authorize_url: 
      token_url: 
      userdata_url:
      scope:
        - openid
        - profile
        - email
      username_key: preferred_username
    JupyterHub:
      authenticator_class: generic-oauth
  extraConfig:
    myConfig.py: |
      c.Spawner.cmd = ['jupyter-labhub']


proxy:
  secretToken: "<openssl rand -hex 32>"
